// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://simfaofvbwyxwyqdxwqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpbWZhb2Z2Ynd5eHd5cWR4d3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjkyNTksImV4cCI6MjA2Mjk0NTI1OX0.n7q0vGk_UYZ8L-JyyiBo6rWD6L2xZT0JCYEW2fYrl1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);